export default {
  login: "boogiedml",
  id: 66917788,
  node_id: "MDQ6VXNlcjY2OTE3Nzg4",
  avatar_url: "https://avatars.githubusercontent.com/u/66917788?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/boogiedml",
  html_url: "https://github.com/boogiedml",
  followers_url: "https://api.github.com/users/boogiedml/followers",
  following_url:
    "https://api.github.com/users/boogiedml/following{/other_user}",
  gists_url: "https://api.github.com/users/boogiedml/gists{/gist_id}",
  starred_url: "https://api.github.com/users/boogiedml/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/boogiedml/subscriptions",
  organizations_url: "https://api.github.com/users/boogiedml/orgs",
  repos_url: "https://api.github.com/users/boogiedml/repos",
  events_url: "https://api.github.com/users/boogiedml/events{/privacy}",
  received_events_url: "https://api.github.com/users/boogiedml/received_events",
  type: "User",
  site_admin: false,
  name: "Sherifdeen Ishola",
  company: null,
  blog: "",
  location: "Nigeria",
  email: null,
  hireable: null,
  bio: "Web Developer | Mindset Enthusiast | Growth Expert",
  twitter_username: "boogiedml",
  public_repos: 13,
  public_gists: 0,
  followers: 5,
  following: 5,
  created_at: "2020-06-14T17:34:30Z",
  updated_at: "2022-10-07T19:36:31Z",
};
